import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    Brand: "Huawei",
   Name: "P40 Pro",
   Image: "https://m.media-amazon.com/images/I/61VX0szn4aL._SL1000_.jpg",
   Storage: "256GB",
   Price: "899",
   ScreenSize: "6.58 inches",
   RAM: "8GB",
   OperatingSystem: "MIUI",
   Camera: "Quad 50MP rear, 32MP front",
   BatteryCapacity: "4,200mAh",
    ratings: {
      value: "3.5",
      count: "2345",
    },
    inStock: true,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    Brand: "Motorola",
   Name: "Moto G Power (2022)",
   Image: "https://m.media-amazon.com/images/I/61I2yy1G57L._AC_SL1500_.jpg",
   Storage: "64GB",
   Price: "249",
   ScreenSize: "6.6 inches",
   RAM: "4GB",
   OperatingSystem: "Android",
   Camera: "Quad 48MP rear, 8MP front",
   BatteryCapacity: "5,000mAh",
    ratings: {
      value: "4.4",
      count: "1982",
    },
    inStock: true,
    isBestSeller: true,
  },
  {
    _id: uuid(),
    Brand: "LG",
   Name: "Velvet 5G",
   Image: "https://m.media-amazon.com/images/I/71epYJfrPnL._SL1500_.jpg",
   Storage: "128GB",
   Price: "599",
   ScreenSize: "6.8 inches",
   RAM: "6GB",
   OperatingSystem: "Android",
   Camera: "Triple 48MP rear, 16MP front",
   BatteryCapacity: "4,300mAh",
   ratings: {
      value: "3.5",
      count: "6041",
    },
    inStock: true,
    isBestSeller: false,

  },
  {
    _id: uuid(),
    Brand: "Sony",
   Name: "Xperia 1 III",
   Image: "https://m.media-amazon.com/images/I/61SPQ9SnfpL._SL1500_.jpg",
   Storage: "256GB",
   Price: "1,299",
   ScreenSize: "6.5 inches",
   RAM: "12GB",
   OperatingSystem: "Android",
   Camera: "Triple 12MP rear, 8MP front",
   BatteryCapacity: "4,500mAh",
    ratings: {
      value: "4.0",
      count: "19820",
    },
    inStock: true,
    isBestSeller: true,
  },
  {
    _id: uuid(),
    Brand: "Xiaomi",
   Name: "Redmi Note 10 Pro",
   Image: "https://m.media-amazon.com/images/I/81aQWPoGdOL._SL1500_.jpg",
   Storage: "128GB",
   Price: "299",
   ScreenSize: "6.67 inches",
   RAM: "6GB",
   OperatingSystem: "MIUI",
   Camera: "Quad 64MP rear, 16MP front",
   BatteryCapacity: "5,020mAh",
    ratings: {
      value: "2.7",
      count: "2980",
    },
    inStock: true,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    Brand: "OnePlus",
    Name: "9 Pro",
   Image: "https://m.media-amazon.com/images/I/61LB+d0vheL._SL1500_.jpg",
    Storage: "256GB",
    Price: "999",
    ScreenSize: "6.7 inches",
    RAM: "12GB",
    OperatingSystem: "OxygenOS",
    Camera: "Quad 48MP rear, 16MP front",
    BatteryCapacity: "4,500mAh",
     ratings: {
      value: "3.2",
      count: "39820",
    },
    inStock: true,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    Brand: "Oppo",
    Name: "Find X3 Pro",
    Image: "https://m.media-amazon.com/images/I/41H-PcHgSuL._AC_.jpg",
    Storage: "256GB",
    Price: "1,199",
    ScreenSize: "6.7 inches",
    RAM: "12GB",
    OperatingSystem: "Android",
   Camera: "50MP ultra-wide-angle",
   BatteryCapacity: "4,500mAh",
    ratings: {
      value: "4.4",
      count: "25820",
    },
    inStock: true,
    isBestSeller: true,
  },
  {
    _id: uuid(),
    Brand: "Google",
    Name: "Pixel 6",
    Image: "https://m.media-amazon.com/images/I/41LBAn9vTuL.jpg",
    Storage: "128GB",
    Price: "799",
    ScreenSize: "6.4 inches",
    RAM: "8GB",
    OperatingSystem: "Android",
    Camera: "Dual 50MP rear, 12MP front",
    BatteryCapacity: "4,614mAh",
     ratings: {
      value: "2.9",
      count: "5820",
    },
    inStock: true,
    isBestSeller: false,
 
  },
  {
    _id: uuid(), 
   Brand: "Samsung",
   Name: "Galaxy S21 Ultra",
   Image: "https://images.samsung.com/is/image/samsung/p6pim/in/sm-g990elviinu/gallery/in-galaxy-s21-fe-g990-sm-g990elviinu-thumb-530606545?imwidth=480",
   Storage: "128GB",
   Price: "1,199",
   ScreenSize: "6.8 inches",
   RAM: "12GB",
   OperatingSystem: "Android",
   Camera: "Quad 108MP rear, 40MP front",
   BatteryCapacity: "5,000mAh",
    ratings: {
      value: "3.5",
      count: "19823",
    },
    inStock: true,
    isBestSeller: false,
  },
  {
    _id: uuid(),
    Brand: "Apple",
    Name: "iPhone 13 Pro",  
    Image: "https://img4.gadgetsnow.com/gd/images/products/additional/small/G306210_View_1/mobiles/smartphones/apple-iphone-13-pro-128-gb-sierra-blue-6-gb-ram-.jpg",
    Storage: "256GB",
    Price: "1,099",
    ScreenSize: "6.1 inches",
    RAM: "6GB",
    OperatingSystem: "iOS",
    Camera: "Triple 12MP rear, 12MP front",
    BatteryCapacity: "3,240mAh",
      ratings: {
      value: "3.6",
      count: "3982",
    },
    inStock: true,
    isBestSeller: false,
  },
];
